# Iris의 세 가지 품종, 분류해볼 수 있겠어요?

## 필요한 모듈 import

In [1]:
from sklearn.datasets import load_digits, load_wine, load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn.linear_model import SGDClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import recall_score
import numpy as np

# Digit

## 데이터 준비

In [2]:
digits = load_digits()

## 데이터 이해

In [3]:
print(dir(digits))

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']


In [4]:
digits.keys()

dict_keys(['data', 'target', 'frame', 'feature_names', 'target_names', 'images', 'DESCR'])

In [5]:
digit_data = digits.data
print(digit_data.shape)

(1797, 64)


In [6]:
digit_data[0]

array([ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10.,
       15.,  5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4.,
       12.,  0.,  0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,
        0.,  0.,  4., 11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5.,
       10., 12.,  0.,  0.,  0.,  0.,  6., 13., 10.,  0.,  0.,  0.])

In [7]:
digit_label = digits.target
print(digit_label.shape)
digit_label

(1797,)


array([0, 1, 2, ..., 8, 9, 8])

In [8]:
digits.target_names

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
print(digits.DESCR)

.. _digits_dataset:

Optical recognition of handwritten digits dataset
--------------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 1797
    :Number of Attributes: 64
    :Attribute Information: 8x8 image of integer pixels in the range 0..16.
    :Missing Attribute Values: None
    :Creator: E. Alpaydin (alpaydin '@' boun.edu.tr)
    :Date: July; 1998

This is a copy of the test set of the UCI ML hand-written digits datasets
https://archive.ics.uci.edu/ml/datasets/Optical+Recognition+of+Handwritten+Digits

The data set contains images of hand-written digits: 10 classes where
each class refers to a digit.

Preprocessing programs made available by NIST were used to extract
normalized bitmaps of handwritten digits from a preprinted form. From a
total of 43 people, 30 contributed to the training set and different 13
to the test set. 32x32 bitmaps are divided into nonoverlapping blocks of
4x4 and the number of on pixels are counted in each blo

## train, test 데이터 분리

In [10]:
X_train, X_test, y_train, y_test = train_test_split(digit_data, 
                                                    digit_label, 
                                                    test_size=0.2, 
                                                    random_state=777)

print('X_train 개수: ', len(X_train),', X_test 개수: ', len(X_test))

X_train 개수:  1437 , X_test 개수:  360


In [11]:
X_train.shape, y_train.shape

((1437, 64), (1437,))

In [12]:
X_test.shape, y_test.shape

((360, 64), (360,))

In [13]:
y_train, y_test

(array([3, 5, 6, ..., 7, 9, 3]),
 array([5, 6, 6, 2, 4, 1, 7, 3, 4, 3, 4, 7, 4, 2, 2, 6, 3, 7, 1, 2, 3, 2,
        0, 2, 6, 1, 9, 7, 7, 8, 4, 5, 8, 3, 7, 5, 9, 8, 7, 8, 7, 1, 1, 4,
        7, 8, 2, 5, 8, 6, 8, 5, 0, 7, 4, 6, 3, 1, 7, 6, 6, 6, 4, 6, 7, 0,
        9, 2, 7, 5, 1, 5, 5, 9, 4, 2, 4, 4, 0, 7, 3, 8, 0, 8, 6, 6, 3, 9,
        9, 3, 6, 1, 0, 9, 8, 7, 4, 0, 3, 9, 7, 4, 9, 8, 1, 0, 7, 6, 0, 8,
        5, 1, 5, 5, 9, 7, 2, 6, 1, 0, 2, 1, 0, 8, 0, 7, 9, 3, 8, 1, 0, 1,
        4, 9, 3, 4, 7, 9, 6, 4, 7, 5, 9, 5, 3, 7, 8, 8, 3, 2, 7, 5, 8, 5,
        0, 5, 4, 6, 3, 1, 9, 4, 5, 8, 8, 6, 9, 3, 7, 7, 6, 1, 6, 9, 6, 5,
        7, 1, 1, 0, 2, 1, 3, 0, 1, 4, 1, 0, 6, 8, 9, 8, 8, 4, 7, 6, 0, 8,
        8, 6, 8, 5, 5, 5, 7, 0, 3, 1, 9, 0, 3, 5, 2, 8, 0, 9, 0, 1, 7, 6,
        8, 0, 0, 8, 0, 6, 7, 5, 5, 1, 1, 5, 7, 3, 7, 8, 0, 0, 6, 8, 2, 6,
        2, 2, 9, 9, 0, 8, 4, 7, 1, 3, 0, 1, 9, 2, 1, 1, 0, 8, 8, 7, 3, 1,
        5, 4, 0, 9, 5, 2, 2, 7, 7, 5, 9, 8, 9, 2, 5, 4, 4, 2, 3, 0, 8, 1,
     

In [14]:
# 정규화
X_train_norm, X_test_norm = X_train / np.max(X_train), X_test / np.max(X_test)

## 다양한 모델 학습 및 평가

In [15]:
# Decision Tree
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_train_norm, y_train)
decision_tree_y_pred = decision_tree.predict(X_test_norm)
print(classification_report(y_test, decision_tree_y_pred))
print('-----------------------Decision Tree-------------------------')

# RandomForest
random_forest = RandomForestClassifier(random_state=42)
random_forest.fit(X_train_norm, y_train)
random_forest_y_pred = random_forest.predict(X_test_norm)
print(classification_report(y_test, random_forest_y_pred))
print('-----------------------RandomForest--------------------------')

# SVM
svm_model = svm.SVC()
svm_model.fit(X_train_norm, y_train)
svm_y_pred = svm_model.predict(X_test_norm)
print(classification_report(y_test, svm_y_pred))
print('----------------------------SVM------------------------------')

# SGD
sgd_model = SGDClassifier()
sgd_model.fit(X_train_norm, y_train)
sgd_y_pred = sgd_model.predict(X_test_norm)
print(classification_report(y_test, sgd_y_pred))
print('----------------------------SGD------------------------------')

# Logistic Regression
logistic_model = LogisticRegression(max_iter=256)
logistic_model.fit(X_train_norm, y_train)
logistic_y_pred = logistic_model.predict(X_test_norm)
print(classification_report(y_test, logistic_y_pred))
print('--------------------Logistic Regression----------------------')

              precision    recall  f1-score   support

           0       0.97      0.97      0.97        38
           1       0.76      0.86      0.81        36
           2       0.87      0.84      0.86        32
           3       0.82      1.00      0.90        27
           4       0.79      0.84      0.82        32
           5       0.93      0.88      0.90        42
           6       0.94      0.89      0.91        36
           7       0.89      0.87      0.88        39
           8       0.91      0.75      0.82        40
           9       0.82      0.82      0.82        38

    accuracy                           0.87       360
   macro avg       0.87      0.87      0.87       360
weighted avg       0.87      0.87      0.87       360

-----------------------Decision Tree-------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        38
           1       0.84      1.00      0.91        36
           2    

# Wine

## 데이터 준비

In [16]:
wines = load_wine()

## 데이터 이해

In [17]:
print(dir(wines))

['DESCR', 'data', 'feature_names', 'frame', 'target', 'target_names']


In [18]:
wines.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names'])

In [19]:
wine_data = wines.data
print(wine_data.shape)

(178, 13)


In [20]:
wine_data[0]

array([1.423e+01, 1.710e+00, 2.430e+00, 1.560e+01, 1.270e+02, 2.800e+00,
       3.060e+00, 2.800e-01, 2.290e+00, 5.640e+00, 1.040e+00, 3.920e+00,
       1.065e+03])

In [21]:
wine_label = wines.target
print(wine_label.shape)
wine_label

(178,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [22]:
wines.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [23]:
print(wines.DESCR)

.. _wine_dataset:

Wine recognition dataset
------------------------

**Data Set Characteristics:**

    :Number of Instances: 178 (50 in each of three classes)
    :Number of Attributes: 13 numeric, predictive attributes and the class
    :Attribute Information:
 		- Alcohol
 		- Malic acid
 		- Ash
		- Alcalinity of ash  
 		- Magnesium
		- Total phenols
 		- Flavanoids
 		- Nonflavanoid phenols
 		- Proanthocyanins
		- Color intensity
 		- Hue
 		- OD280/OD315 of diluted wines
 		- Proline

    - class:
            - class_0
            - class_1
            - class_2
		
    :Summary Statistics:
    
    ============================= ==== ===== ======= =====
                                   Min   Max   Mean     SD
    ============================= ==== ===== ======= =====
    Alcohol:                      11.0  14.8    13.0   0.8
    Malic Acid:                   0.74  5.80    2.34  1.12
    Ash:                          1.36  3.23    2.36  0.27
    Alcalinity of Ash:            1

In [24]:
wines.feature_names

['alcohol',
 'malic_acid',
 'ash',
 'alcalinity_of_ash',
 'magnesium',
 'total_phenols',
 'flavanoids',
 'nonflavanoid_phenols',
 'proanthocyanins',
 'color_intensity',
 'hue',
 'od280/od315_of_diluted_wines',
 'proline']

## train, test 데이터 분리

In [25]:
X_train, X_test, y_train, y_test = train_test_split(wine_data, 
                                                    wine_label, 
                                                    test_size=0.2, 
                                                    random_state=777)

print('X_train 개수: ', len(X_train),', X_test 개수: ', len(X_test))

X_train 개수:  142 , X_test 개수:  36


In [26]:
X_train.shape, y_train.shape

((142, 13), (142,))

In [27]:
X_test.shape, y_test.shape

((36, 13), (36,))

In [28]:
y_train, y_test

(array([0, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0, 2, 2, 0, 0, 2, 0, 0, 1, 2, 2, 0,
        0, 0, 2, 1, 1, 1, 2, 2, 2, 2, 1, 0, 2, 1, 2, 1, 1, 2, 1, 2, 2, 0,
        0, 0, 2, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 2, 1, 0, 0, 0, 1, 2, 0,
        1, 0, 1, 2, 0, 2, 1, 1, 2, 2, 1, 1, 0, 2, 1, 0, 0, 0, 1, 1, 2, 1,
        1, 1, 1, 0, 1, 0, 0, 2, 0, 1, 1, 0, 2, 0, 1, 1, 1, 0, 1, 1, 1, 0,
        1, 1, 1, 0, 2, 1, 2, 0, 2, 0, 1, 1, 1, 1, 1, 0, 2, 2, 2, 0, 0, 0,
        2, 1, 1, 2, 1, 1, 2, 1, 0, 1]),
 array([0, 0, 2, 1, 0, 0, 1, 0, 1, 2, 2, 2, 0, 1, 2, 2, 2, 1, 1, 1, 1, 1,
        1, 1, 0, 0, 2, 0, 2, 1, 1, 0, 2, 1, 1, 0]))

## 다양한 모델 학습 및 평가

In [29]:
# Decision Tree
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_train, y_train)
decision_tree_y_pred = decision_tree.predict(X_test)
print(classification_report(y_test, decision_tree_y_pred))
print('-----------------------Decision Tree-------------------------')

# RandomForest
random_forest = RandomForestClassifier(random_state=42)
random_forest.fit(X_train, y_train)
random_forest_y_pred = random_forest.predict(X_test)
print(classification_report(y_test, random_forest_y_pred))
print('-----------------------RandomForest--------------------------')

# SVM
svm_model = svm.SVC()
svm_model.fit(X_train, y_train)
svm_y_pred = svm_model.predict(X_test)
print(classification_report(y_test, svm_y_pred))
print('----------------------------SVM------------------------------')

# SGD
sgd_model = SGDClassifier()
sgd_model.fit(X_train, y_train)
sgd_y_pred = sgd_model.predict(X_test)
print(classification_report(y_test, sgd_y_pred))
print('----------------------------SGD------------------------------')

# Logistic Regression
logistic_model = LogisticRegression(max_iter=4096)
logistic_model.fit(X_train, y_train)
logistic_y_pred = logistic_model.predict(X_test)
print(classification_report(y_test, logistic_y_pred))
print('--------------------Logistic Regression----------------------')

              precision    recall  f1-score   support

           0       0.92      1.00      0.96        11
           1       1.00      0.87      0.93        15
           2       0.91      1.00      0.95        10

    accuracy                           0.94        36
   macro avg       0.94      0.96      0.95        36
weighted avg       0.95      0.94      0.94        36

-----------------------Decision Tree-------------------------
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        11
           1       1.00      1.00      1.00        15
           2       1.00      1.00      1.00        10

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36

-----------------------RandomForest--------------------------
              precision    recall  f1-score   support

           0       0.82      0.82      0.82        11
     

# Breast Cancer

## 데이터 준비

In [30]:
breast_cancer = load_breast_cancer()

## 데이터 이해

In [31]:
print(dir(breast_cancer))

['DESCR', 'data', 'data_module', 'feature_names', 'filename', 'frame', 'target', 'target_names']


In [32]:
breast_cancer.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [33]:
breast_cancer_data = breast_cancer.data
print(breast_cancer_data.shape) 

(569, 30)


In [34]:
breast_cancer_data[0]

array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01])

In [35]:
breast_cancer_label = breast_cancer.target
print(breast_cancer_label.shape)
breast_cancer_label

(569,)


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [36]:
breast_cancer.target_names

array(['malignant', 'benign'], dtype='<U9')

In [37]:
print(breast_cancer.DESCR)

.. _breast_cancer_dataset:

Breast cancer wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

    :Number of Instances: 569

    :Number of Attributes: 30 numeric, predictive attributes and the class

    :Attribute Information:
        - radius (mean of distances from center to points on the perimeter)
        - texture (standard deviation of gray-scale values)
        - perimeter
        - area
        - smoothness (local variation in radius lengths)
        - compactness (perimeter^2 / area - 1.0)
        - concavity (severity of concave portions of the contour)
        - concave points (number of concave portions of the contour)
        - symmetry
        - fractal dimension ("coastline approximation" - 1)

        The mean, standard error, and "worst" or largest (mean of the three
        worst/largest values) of these features were computed for each image,
        resulting in 30 features.  For instance, field 0 is Mean Radi

In [38]:
breast_cancer.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [39]:
breast_cancer.filename

'breast_cancer.csv'

## train, test 데이터 분리

In [40]:
X_train, X_test, y_train, y_test = train_test_split(breast_cancer_data, 
                                                    breast_cancer_label, 
                                                    test_size=0.2, 
                                                    random_state=777)

print('X_train 개수: ', len(X_train),', X_test 개수: ', len(X_test))

X_train 개수:  455 , X_test 개수:  114


In [41]:
X_train.shape, y_train.shape

((455, 30), (455,))

In [42]:
X_test.shape, y_test.shape

((114, 30), (114,))

In [43]:
y_train, y_test

(array([1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1,
        0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
        0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0,
        1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1,
        1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0,
        1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
        0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 

## 다양한 모델 학습 및 평가

In [44]:
# Decision Tree
decision_tree = DecisionTreeClassifier(random_state=42)
decision_tree.fit(X_train, y_train)
decision_tree_y_pred = decision_tree.predict(X_test)
print(classification_report(y_test, decision_tree_y_pred))
print('-----------------------Decision Tree-------------------------')

# RandomForest
random_forest = RandomForestClassifier(random_state=42)
random_forest.fit(X_train, y_train)
random_forest_y_pred = random_forest.predict(X_test)
print(classification_report(y_test, random_forest_y_pred))
print('-----------------------RandomForest--------------------------')

# SVM
svm_model = svm.SVC()
svm_model.fit(X_train, y_train)
svm_y_pred = svm_model.predict(X_test)
print(classification_report(y_test, svm_y_pred))
print('----------------------------SVM------------------------------')

# SGD
sgd_model = SGDClassifier()
sgd_model.fit(X_train, y_train)
sgd_y_pred = sgd_model.predict(X_test)
print(classification_report(y_test, sgd_y_pred))
print('----------------------------SGD------------------------------')

# Logistic Regression
logistic_model = LogisticRegression(max_iter=4096)
logistic_model.fit(X_train, y_train)
logistic_y_pred = logistic_model.predict(X_test)
print(classification_report(y_test, logistic_y_pred))
print('--------------------Logistic Regression----------------------')

              precision    recall  f1-score   support

           0       0.80      0.87      0.84        38
           1       0.93      0.89      0.91        76

    accuracy                           0.89       114
   macro avg       0.87      0.88      0.87       114
weighted avg       0.89      0.89      0.89       114

-----------------------Decision Tree-------------------------
              precision    recall  f1-score   support

           0       0.94      0.87      0.90        38
           1       0.94      0.97      0.95        76

    accuracy                           0.94       114
   macro avg       0.94      0.92      0.93       114
weighted avg       0.94      0.94      0.94       114

-----------------------RandomForest--------------------------
              precision    recall  f1-score   support

           0       1.00      0.71      0.83        38
           1       0.87      1.00      0.93        76

    accuracy                           0.90       114
   m

# 회고

iris 데이터를 시작으로 sklearn.dataset의 3가지 데이터셋을 기반으로 5가지 모델을 다뤄보고 그에 따른 평가를 내려 어떤 모델이 성능이 좋고, 어떠한 지표가 맞는지를 찾아보았다.
손글씨의 경우 SVM이 가장 좋았고 recall지표를 기준으로 성능을 판단할 것이다.
와인의 경우에는 RandomForest가 좋았으며 역시나 recall을 기준으로 성능을 판단하였다.
마지막으로 유방암의 경우에도 RandomForest가 좋았으며 이건 양성-양성 판단도 중요하지만 음성-음성 판단경우도 생각하여 accuracy가 좋다고 본다.